name: soul_trip
description: "Soul Trip is a specialized Flutter application designed to be the ultimate gateway to wellness tourism in Egypt, connecting international travelers with expert therapists and diverse healing sanctuaries nationwide."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

#--------------------------- Packages -------------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  solar_icon_pack: ^0.2.1
  flutter_screenutil: ^5.9.0
  get_it: ^9.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  connectivity_plus: ^7.0.0
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  go_router: ^17.0.0
  flutter_easyloading: ^3.0.5
  motion_toast: ^2.14.0
  animated_text_kit: ^4.3.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  animate_do: ^4.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^4.2.1

#--------------------------- ./ Packages END -------------------------------#
dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

#--------------------------- App Config ------------------------------------#
flutter:
  uses-material-design: true # CRITICAL: - DO NOT REMOVE
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
  # CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # FONTS:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Soultrip
      fonts:
        - asset: assets/icons/fonts/Soultrip.ttf
